-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 06:53:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bodegas` (
  `idBodega` INT NOT NULL,
  `bodegaNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lineas` (
  `idLinea` INT NOT NULL,
  `lineascol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLinea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cepas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cepas` (
  `idCepa` INT NOT NULL,
  `nombreCepa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCepa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maridaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maridaje` (
  `idmaridaje` INT NOT NULL,
  `maridaje` VARCHAR(200) NULL,
  PRIMARY KEY (`idmaridaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nombreVinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nombreVinos` (
  `idnombreVinos` INT NOT NULL,
  `nombreVinoscol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idnombreVinos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`vinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vinos` (
  `idVino` INT NOT NULL AUTO_INCREMENT,
  `nombreBodega_idBodega` INT NOT NULL,
  `lineas_idLineas` INT NOT NULL,
  `cepas_idCepa` INT NOT NULL,
  `anio` INT NOT NULL,
  `maridaje_idmaridaje` INT NOT NULL,
  `potencialGuardado` INT NULL,
  `descripcion` VARCHAR(200) NULL,
  `volumen` INT NULL,
  `precio` INT NULL,
  PRIMARY KEY (`idVino`),
  CONSTRAINT `fk_vinos_nombreBodega`
    FOREIGN KEY (`nombreBodega_idBodega`)
    REFERENCES `mydb`.`bodegas` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vinos_lineas1`
    FOREIGN KEY (`lineas_idLineas`)
    REFERENCES `mydb`.`lineas` (`idLinea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vinos_cepas1`
    FOREIGN KEY (`cepas_idCepa`)
    REFERENCES `mydb`.`cepas` (`idCepa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vinos_maridaje1`
    FOREIGN KEY (`maridaje_idmaridaje`)
    REFERENCES `mydb`.`maridaje` (`idmaridaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vinos_nombreBodega_idx` ON `mydb`.`vinos` (`nombreBodega_idBodega` ASC);

CREATE INDEX `fk_vinos_lineas1_idx` ON `mydb`.`vinos` (`lineas_idLineas` ASC);

CREATE INDEX `fk_vinos_cepas1_idx` ON `mydb`.`vinos` (`cepas_idCepa` ASC);

CREATE INDEX `fk_vinos_maridaje1_idx` ON `mydb`.`vinos` (`maridaje_idmaridaje` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(200) NOT NULL,
  `avatar` VARCHAR(100) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idPedidos` INT NOT NULL,
  `usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_idUsuarios`)
    REFERENCES `mydb`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedidos_usuarios1_idx` ON `mydb`.`pedidos` (`usuarios_idUsuarios` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`IntPedidosVinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IntPedidosVinos` (
  `idIntPedidosVinos` INT NOT NULL,
  `pedidos_idPedidos` INT NOT NULL,
  `vinos_idVino` INT NOT NULL,
  PRIMARY KEY (`idIntPedidosVinos`),
  CONSTRAINT `fk_IntPedidosVinos_pedidos1`
    FOREIGN KEY (`pedidos_idPedidos`)
    REFERENCES `mydb`.`pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IntPedidosVinos_vinos1`
    FOREIGN KEY (`vinos_idVino`)
    REFERENCES `mydb`.`vinos` (`idVino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_IntPedidosVinos_pedidos1_idx` ON `mydb`.`IntPedidosVinos` (`pedidos_idPedidos` ASC);

CREATE INDEX `fk_IntPedidosVinos_vinos1_idx` ON `mydb`.`IntPedidosVinos` (`vinos_idVino` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
